vaadin.launch-browser=true
spring.application.name=project_TT

spring.datasource.url=jdbc:postgresql://traveltime-db.cjysoyumeqwy.eu-north-1.rds.amazonaws.com/travelTimeDB
spring.datasource.username=postgres
spring.datasource.password=DanPro57
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA ????????? (???? ??????????? Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


